### PR TITLE
Adding serverside rendering with hapi-react-views

### PR DESCRIPTION
**Pull request by leftieFriele**
Added sample along side the original for serverside rendering using hapi-react-views.

This is just simple rendering, I could make an isomorphic version too if you think it's worth while.

### CODE REVIEW

**Comment by franvarney** [comment]
:+1: for isomorphic version

**Comment by lynnaloo** [comment]
Thanks for this @leftieFriele! I really like what you did here (and a few people have requested this), but for now I want to keep the rendering on the client in the master branch. What do you think about maintaining an isomorphic fork (iso-mullet!) and I'll link to it from the README.md here for those who are looking for an isomorphic example?

**Comment by leftieFriele** [comment]
Thanks for the reply.
I think it'll be hard for me to keep up with changes you make to the
project in a fork, so I'll give that a pass for now.
Feel free to use the code for am isomorphic mullet project or similar :)

**Comment by lynnaloo** [comment]
I added a link to this branch to the README.md. Thanks again!

**Pull request closed without merging**
